// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Abstractions.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class EventPayload : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""EventPayload"",""namespace"":""Abstractions.Events"",""fields"":[{""name"":""DataSchema"",""doc"":""The schema of the value in the 'Data' field"",""default"":null,""type"":""string""},{""name"":""Data"",""doc"":""The data of this payload"",""default"":null,""type"":""bytes""}]}");
		/// <summary>
		/// The schema of the value in the 'Data' field
		/// </summary>
		private string _DataSchema;
		/// <summary>
		/// The data of this payload
		/// </summary>
		private byte[] _Data;
		public virtual Schema Schema
		{
			get
			{
				return EventPayload._SCHEMA;
			}
		}
		/// <summary>
		/// The schema of the value in the 'Data' field
		/// </summary>
		public string DataSchema
		{
			get
			{
				return this._DataSchema;
			}
			set
			{
				this._DataSchema = value;
			}
		}
		/// <summary>
		/// The data of this payload
		/// </summary>
		public byte[] Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				this._Data = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.DataSchema;
			case 1: return this.Data;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.DataSchema = (System.String)fieldValue; break;
			case 1: this.Data = (System.Byte[])fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
